### ISSUE TITLE
Parsed HTML is being prettified for seemingly no reason

### ISSUE THREAD

**Issue by merlin-ka** [JoHoop/studip-sync#6]
Is there a reason why the parsed HTML is being prettified and then parsed again?

https://github.com/JoHoop/studip-sync-files/blob/9c31bee55ea5fa77ca126d60b1cf87b508279d2e/studip-sync.py#L54-L55

**Comment by JoHoop** [comment]
> Is there a reason why the parsed HTML is being prettified and then parsed again?

Right! I've fixed it. Thanks

`pretty_content = parsed_content.prettify()`

**Comment by merlin-ka** [comment]
Now you're trying to work on `pretty_content` as if it was a `BeautifulSoup` object even though it's a string... The idea was removing `pretty_content` completely and using `parsed_content` instead.

This fix does not work since you're trying to use `BeautifulSoup` methods such as `.find()` on a string.

**Comment by JoHoop** [comment]
Great stuff! Thanks a lot @gura-ch
